# Generated by Django 4.1.7 on 2023-04-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbl5app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url_video',
            field=models.FileField(blank=True, null=True, upload_to='static/videos/'),
        ),
    ]
