# Generated by Django 4.1.7 on 2023-05-06 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pbl5app', '0003_alter_user_url_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListEncode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encode', models.TextField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbl5app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pbl5app.user')),
            ],
        ),
    ]
