# Generated by Django 4.1.7 on 2023-05-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbl5app', '0005_rename_id_user_attendance_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='listencode',
            name='user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='id_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listencode',
            name='id_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
